# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'mobile_de'
version: '1.3.1'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt-bq'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]