dbt-bq:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('gcp_project_id') }}"
      dataset: dev
      threads: 4
      keyfile: /secret/SA_KEY
      timeout_seconds: 300
      priority: interactive
      retries: 1
    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('gcp_project_id') }}"
      dataset: prod
      threads: 4
      keyfile: /secret/SA_KEY
      timeout_seconds: 300
      priority: interactive
      retries: 1