dbt-bq:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('gcp_project_id') }}"
      dataset: dev
      threads: 4
      keyfile: /secrets/sa_key
      timeout_seconds: 300
      priority: interactive
      retries: 1
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('gcp_project_id') }}"
      dataset: prod
      threads: 4
      keyfile: /secrets/sa_key
      timeout_seconds: 300
      priority: interactive
      retries: 1