version: 2

sources:
  - name: prod
    database: "{{ env_var('gcp_project_id') }}"
    schema: prod
    tables:
      - name: raw_playlist_data
        description: Raw Playlist data
  - name: dev
    database: "{{ env_var('gcp_project_id') }}"
    schema: dev
    tables:
      - name: raw_playlist_data
        description: Test Raw Playlist data